### ISSUE TITLE
Display something other then the time?

### ISSUE THREAD

**Issue by whoman321** [arthur-liberman/linux_openvfd#10]
Hello!

Would it be possible to display numbers on the time display through userspace?

I see that in Demo mode the OpenVFDService does rotate through a number of different character output on the HH:MM, however I can't really see how I could modify that to achieve my goal.

I'm using a python script for my box, and I'd like to send something other then time, for example, the cpu temp to HH and cpu usage to MM.

I can get those values in my python script, but I'm not sure how to send them to the HH:MM display

Ideally I'd like to populate those two values (HH and MM) separately.

Since I'm using python, I can easily enable and disable the other leds (wifi, eth, etc) by executing the usual command line command:

`echo wifi > /sys/class/leds/openvfd/led_on`

Is there a way I can send the temperature in a similar way through a command line command, or if not, directly through python?

If you could point me in the right direction, I'd be super appreciative.

Thanks so much for all hard work.

**Comment by whoman321** [comment]
Solved this by hacking OpenVFDService to feed 2 command line variables to time_date.hours and time_date.minutes.

**Comment by bk3a12** [comment]
Hello all,
I managed to let temperature show up on the disokay. But I wasn't able to show degree symbol (°C) on time_date.minutes. Could you please guide me with that?
Thank you!

**Comment by arthur-liberman** [comment]
Ascii value 176 should print degree sign.

**Comment by bk3a12** [comment]
Thank you for replying. Actually, I did try to add ascii value to time_date.minutes like this:
1)
char degree = 176;
time_date.minutes = degree;
--> This will print value 76 to minutes LED.
2)
char sign = 'C';
time_date.minutes = sign;
--> This will print value 67 to minutes LED.

Can you tell me what I'm doing wrong?
