### ISSUE TITLE
What is the required file ?

### ISSUE THREAD

**Issue by sajati** [arthur-liberman/linux_openvfd#21]
i tested it on armbian, it runs sucessfully, then
trying to run on openwrt (using the same armbian kernel) got this error :

`-bash: /usr/bin/OpenVFDService: cannot execute: required file not found`

i make sure :
/storage/.config/vfd.conf is exist 
module openvfd.ko is loaded

perhaps copying that "required file" from armbian to openwrt make it able to run on openwrt ?

**Comment by arthur-liberman** [comment]
This is a system error. And from my limited search of what this error could mean, it's possible that there's a missing dependency in the OS itself which causes this error.
Maybe there are some system logs you can look at to see why the application failed to start.
