### ISSUE TITLE
RK3566 - "periphs-banks" chip not found (multiple banks issue, new $ARCH?)

### ISSUE THREAD

**Issue by rossbcan** [arthur-liberman/linux_openvfd#22]
Hi Arthur;

I am using armbian on a H96 Max V56 (rk3566, FD6551, kernel 6.2) box with your latest openvfd. Am planning to do so for V58 (rk3588) also.

Here's the log:
`
[ 1240.658303] OpenVFD: Version: V1.4.4
[ 1240.658347] OpenVFD: vfd_gpio_clk:           #0 = 0x00; #1 = 0x0B; #2 = 0x00;
[ 1240.658367] OpenVFD: vfd_gpio_dat:           #0 = 0x00; #1 = 0x0C; #2 = 0x00;
[ 1240.658384] OpenVFD: vfd_gpio_stb:           #0 = 0x00; #1 = 0x00; #2 = 0xFF;
[ 1240.658400] OpenVFD: vfd_gpio0:              #0 = 0x00; #1 = 0x00; #2 = 0xFF;
[ 1240.658416] OpenVFD: vfd_gpio1:              #0 = 0x00; #1 = 0x00; #2 = 0xFF;
[ 1240.658430] OpenVFD: vfd_gpio2:              #0 = 0x00; #1 = 0x00; #2 = 0xFF;
[ 1240.658444] OpenVFD: vfd_gpio3:              #0 = 0x00; #1 = 0x00; #2 = 0xFF;
[ 1240.658459] OpenVFD: vfd_gpio_protocol:      #0 = 0x00; #1 = 0x00;
[ 1240.658475] OpenVFD: vfd_chars:              #0 = 0x00; #1 = 0x01; #2 = 0x02; #3 = 0x03; #4 = 0x04;
[ 1240.658496] OpenVFD: vfd_dot_bits:           #0 = 0x00; #1 = 0x00; #2 = 0x00; #3 = 0x06; #4 = 0x05; #5 = 0x00; #6 = 0x00;
[ 1240.658514] OpenVFD: vfd_display_type:       #0 = 0x01; #1 = 0x00; #2 = 0x00; #3 = 0x06;
[ 1240.658534] OpenVFD: Detected gpio chips:    gpio0, gpio1, gpio2, gpio3, gpio4.
[ 1240.658546] OpenVFD: "periphs-banks" chip was not found
[ 1240.658555] OpenVFD: Could not get pin number for vfd_gpio_clk
[ 1240.659092] OpenVFD: Failed to verify VFD configuration file, attempt using device tree as fallback.
[ 1240.659903] OpenVFD: openvfd_gpio_clk pin entry not found
[ 1240.659913] OpenVFD: openvfd_gpio_dat pin entry not found
[ 1240.659922] OpenVFD: openvfd_gpio_stb pin entry not found
[ 1240.659931] OpenVFD: openvfd_gpio0 pin entry not found
[ 1240.659940] OpenVFD: openvfd_gpio1 pin entry not found
[ 1240.659948] OpenVFD: openvfd_gpio2 pin entry not found
[ 1240.659957] OpenVFD: openvfd_gpio3 pin entry not found
[ 1240.659967] OpenVFD: can't find openvfd_chars list, falling back to defaults.
[ 1240.659974] OpenVFD: chars_prop = 0000000000000000
[ 1240.660704] OpenVFD: can't find openvfd_dot_bits list, falling back to defaults.
[ 1240.660715] OpenVFD: dot_bits_prop = 0000000000000000
[ 1240.661381] OpenVFD: display.type = 0, display.controller = 0, pdata->dev->dtb_active.display.flags = 0x00
[ 1240.661397] OpenVFD: can't request gpio of gpio_clk
[ 1240.661411] openvfd: probe of openvfd failed with error -22`

It seems that openvfd (openvfd_drv.c, line ~700) should be using (or iterating over) the "Detected gpio chips:    gpio0, gpio1, gpio2, gpio3, gpio4" for pin verification as opposed to entries from "const char *pin_banks[] = { "periphs-banks", "aobus-banks", "gpio0", "gpio1", "gpio2", "gpio3" };"

root@box:~# ls /dev/ | grep gpio
gpiochip0
gpiochip1
gpiochip2
gpiochip3
gpiochip4

I am willing to test any suggestions you may have. Would you like me to alter the pin_banks[] declaration to remove "periphs-banks", "aobus-banks"? Perhaps this can be handled with $ARCH def's?

A search of issues for rk3566 yields nada, so, this appears to be a new openvfd target $ARCH.

Thanks;
Bill

**Comment by arthur-liberman** [comment]
The original code was written to work with old Amlogic chips, and I didn't think about the possibility that GPIOs may be renamed and/or be different on newer kernels or other platforms. This allowed me to use a simple numeric index to select the gpio chip in the configuration.
To fix this, I added a new optional kernel parameter that lets you specify the gpio name you need. `vfd_gpio_chip_name`

**Comment by rossbcan** [comment]
That was quite prescient of you. Result:
![image](https://github.com/arthur-liberman/linux_openvfd/assets/13289915/adc56ae6-9ce6-4246-9fbf-e13373e858aa)

I need to tweak display parms, but detected and initialized. Thanks; closing issue...

Regards;
Bill
