### ISSUE TITLE
OpenVFD: Failed to verify VFD configuration file, attempt using device tree as fallback.

### ISSUE THREAD

**Issue by rossbcan** [arthur-liberman/linux_openvfd#3]
Hi Arthur;

Tanix Tx92, Armbian Ubuntu bionic (built linux_openvfd)

Thank you very much for linux_openvfd.
It appears my config file for TX92: https://github.com/arthur-liberman/vfd-configurations/blob/master/tx92-vfd.conf

is not being read or is incorrect, leading to topic title. I tried the following locations:
/storage/.config/vfd.conf
/.config/vfd.conf
and in same directory as OpenVFDService

to no avail. I even tried fgrep -r vfd.conf in the build directory, in case the path was changed. No references in source or object files.

has vfd.conf been renamed, moved, or obsoleted?

My dtb handles this OK, but I want to avoid a dtb per target, take care of vfd layout using conf file.

Your thoughts?
Thanks, Bill

**Comment by arthur-liberman** [comment]
Hi Bill,

Is the openvfd service running? You can try to run `systemctl status openvfd` to get a reading on what exactly is going wrong.
` /storage/.config/` is the path *ELEC OSes use for config files, you can change it in the openvfd system.d openvfd.service file.
You can also try to load the module manually in a similar fashion to how the system.d service does it and see what happens.

Thanks, Arthur

**Comment by rossbcan** [comment]
Hi Arthur;

Thanks; misc-comprehension on my part regarding how the openvfd module is configured - intent is to pass config as modprobe parameters. Once I inspected  *ELEC OS service file, very clear.

So, created my own services file (/etc/systemd/system/openvfd.service):
`[Unit]
Description=openvfd
Wants=network-online.target

[Service]
Type=simple
Environment="OPTS=-12h"
ExecStartPre=/bin/sh -c ". /etc/vfd.conf; /sbin/modprobe openvfd vfd_gpio_clk=$vfd_gpio_clk vfd_gpio_dat=$vfd_gpio_dat vfd_gpio_stb=$vfd_gpio_stb vfd_chars=$vfd_chars vfd_dot_bits=$vfd_dot_bits vfd_display_type=$vfd_display_type;"
ExecStart=/usr/bin/OpenVFDService $OPTS &
ExecStop=/usr/bin/killall OpenVFDService
ExecStopPost=-/sbin/rmmod openvfd

[Install]
WantedBy=multi-user.target
`
...,and this "my issue" resolved

Let me know if any suggested changes to above file.
hope this helps someone else...

Regards;
Bill

**Comment by ataa** [comment]
@rossbcan Can you share the steps required to install or activate OpenVFD on Armbian? I couldn't find any package to install it and not familiar with compiling kernel modules on ARM.
I ran "locate vfd" and found these:
/run/udev/data/+platform:meson-vfd
/run/udev/data/+platform:openvfd

on my HK1 X3 box.

Thanks
